groups:
  - name: miniidm
    rules:
      - alert: MiniIdMServiceDown
        expr: miniidm_service_up == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: El servicio MiniIdM no está disponible

      - alert: MiniIdMLdapQueryFailure
        expr: miniidm_ldap_query_success == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Falló la comprobación de consulta LDAP
